TYPO3:
  Flow:
    security:
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              routeValues:
              '@package': 'Refactory.Login'
              '@controller': 'Login'
              '@action': 'index'

Refactory:
  Login:
    partyRepositoryClassName: 'TYPO3\Party\Domain\Repository\PartyRepository'
    tokenExpiration: 14400 # in seconds
    translationPackageKey: 'Refactory.Login'
    translationSourceName: 'Main'


#    image: 'resource://Refactory.Login/Public/Images/ApplicationLogo.png'
#    styles:
#      - resource://Vendor.MyPackage/Public/Styles/Custom.css'
#    authenticatedRedirect:
#      packageKey: Vendor.MyPackage
#      controller: SignedIn
#      actionName: Authenticated
